const requires = [
   { req: require('../../assets/developerPng/React.png'), _title: 'React-Native' },
   { req: require('../../assets/developerPng/Android.png'), _title: 'Android' },
   { req: require('../../assets/developerPng/C.png'), _title: 'C++' },
   { req: require('../../assets/developerPng/Go.png'), _title: 'Go' },
   { req: require('../../assets/developerPng/GraphQL.png'), _title: 'GraphQL' },
   { req: require('../../assets/developerPng/HTML.png'), _title: 'HTML' },
   { req: require('../../assets/developerPng/IOS.png'), _title: 'IOS' },
   { req: require('../../assets/developerPng/Java.png'), _title: 'Java' },
   { req: require('../../assets/developerPng/Javascript.png'), _title: 'Javascript' },
   { req: require('../../assets/developerPng/Kotlin.png'), _title: 'Kotlin' },
   { req: require('../../assets/developerPng/Mongo.png'), _title: 'Mongo' },
   { req: require('../../assets/developerPng/Node.png'), _title: 'Node' },
   { req: require('../../assets/developerPng/Objective.png'), _title: 'Objective C' },
   { req: require('../../assets/developerPng/PostgreS.png'), _title: 'PostgreS' },
   { req: require('../../assets/developerPng/Python.png'), _title: 'Python' },
   { req: require('../../assets/developerPng/React.png'), _title: 'React' },
   { req: require('../../assets/developerPng/Rust.png'), _title: 'Rust' },
   { req: require('../../assets/developerPng/Swift.png'), _title: 'Swift' },
   { req: require('../../assets/developerPng/Typescript.png'), _title: 'Typescript' },
];
const designPng = [
   { req: require('../../assets/designPng/UI.png'), _title: 'UI' },
   { req: require('../../assets/designPng/UX.png'), _title: 'UX' },
   { req: require('../../assets/designPng/Motion.png'), _title: 'Motion' },
   { req: require('../../assets/designPng/Graphic.png'), _title: 'Graphic' },
   { req: require('../../assets/designPng/3D.png'), _title: '3D' },
   { req: require('../../assets/designPng/product.png'), _title: 'Product' },
   { req: require('../../assets/designPng/Figma.png'), _title: 'Figma' },
   { req: require('../../assets/designPng/AdobeXD.png'), _title: 'Adobe XD' },
   { req: require('../../assets/designPng/Sketch.png'), _title: 'Sketch' },
   { req: require('../../assets/designPng/Illustrator.png'), _title: 'Illustrator' },
   { req: require('../../assets/designPng/PhotoShop.png'), _title: 'PhotoShop' },
];

export { requires, designPng };
